# Generated by Django 2.2.5 on 2019-09-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Nome_autor', models.CharField(max_length=200)),
                ('Assunto', models.CharField(max_length=200)),
                ('Editora', models.CharField(max_length=200)),
                ('ISBN', models.CharField(max_length=20)),
                ('Ano_publicacao', models.DateField()),
            ],
        ),
    ]
