# Generated by Django 2.2.5 on 2019-09-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomec', models.CharField(max_length=80)),
                ('descricaoProduto', models.CharField(max_length=100)),
                ('qtdPrevistoMes', models.FloatField()),
                ('preco', models.FloatField()),
                ('precoMax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datacriacao', models.CharField(max_length=35)),
                ('tipodespesa', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=60)),
                ('formapagamento', models.CharField(max_length=40)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
    ]
